run:
  timeout: 5m
linters:
  enable:
    - goheader
    - revive
    - unused
  disable-all: true
# all available settings of specific linters
linters-settings:
  goheader:
    values:
      regexp:
        copyright-year: 20[0-9][0-9]
    template-path: code-header-template.txt
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    # exclude stuttering linting error
    - ".*and that stutters;.*"
