version: "2"
run:
  timeout: 5m
linters:
  default: none
  enable:
    - goheader
    - revive
    - unused
  settings:
    goheader:
      values:
        regexp:
          copyright-year: 20[0-9][0-9]
      template-path: code-header-template.txt
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: 81ec69d2757c261768a21eef8ff53169e658aad5
