apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-ns-sa
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-ns-role
  namespace: default
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-ns-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default-ns-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-ns-role
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: simple-app-cr
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  fetch:
  - git: {}
  template:
  - ytt: {}
  deploy:
  - kapp: {}
  