name: kapp-external-test-run

on:
  push:
    branches:
      - "v*"
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  kappreleaser:
    name: kapp external tests
    runs-on: ubuntu-latest
    # Set permissions of github token. See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run Test cases
        run: |
          # Setup minikube
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker --memory 4096
          eval $(minikube docker-env --shell=bash)

          # Ensure that there is no existing kapp installed
          rm -f /tmp/bin/kapp

          # Build kapp binary
          set -e -x
          VERSION=`echo ${{ github.ref }}  | grep -Eo '[0-9].*'`
          ./hack/build.sh

          # Add binary to the path
          mkdir bin
          mv kapp bin
          PATH=$PATH:$PWD/bin
          echo $PATH

          # Run test cases
          ./hack/test-external.sh
