---
name: Check inclusive language

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

jobs:
  check-inclusive-language:
    uses: carvel-dev/release-scripts/.github/workflows/inclusive-language-check.yml@main
