name: Run All Tests

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test-all:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        k8s-version: [v1.28.0, latest]
    steps:
    - name: install kind
      uses: helm/kind-action@v1
      with:
        install_only: true
    - name: Resolve Kubernetes version
      id: resolve-k8s-version
      run: |
        k8s_version=${{ matrix.k8s-version }}
        if [ "${k8s_version}" = "latest" ]; then
          k8s_version=$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/kubernetes/kubernetes/releases/latest | grep -oE 'tag/v[0-9]+\.[0-9]+\.[0-9]+' | cut -d'/' -f2)
          echo "Resolved latest k8s version to: $k8s_version"
        fi
        echo "k8s_version=$k8s_version" >> $GITHUB_ENV
    - name: Build and push kind image for latest Kubernetes
      run: |
        k8s_version=v1.35.0-beta.0
        mkdir tmp && cd tmp
        git clone https://github.com/kubernetes/kubernetes.git && cd kubernetes
        git checkout v1.35.0-beta.0
        git clone https://github.com/kubernetes-sigs/kind.git && cd kind
        kind build node-image --type=source $(pwd)/.. --image kindest/node:v1.35.0-beta.0
        docker tag kindest/node:v1.35.0-beta.0 \
          ghcr.io/${{ github.repository_owner }}/kindest-node:v1.35.0-beta.0
        docker push ghcr.io/${{ github.repository_owner }}/kindest-node:v1.35.0-beta.0
        cd $(pwd)/../../../
        rm -rf tmp && echo "Cleanup completed: Temporary directory 'tmp' has been removed." || echo "Cleanup failed: Could not remove 'tmp' directory."
    - name: Create Kind Cluster(k8s version ${{ env.k8s_version }})
      run: |
        k8s_version=${{ env.k8s_version }}
        echo "Checking if kindest/node:${k8s_version} exists..."
        if docker pull kindest/node:${k8s_version}; then
          echo "Using kindest/node:${k8s_version}"
          kind create cluster --image kindest/node:${k8s_version}
        else
          echo "kindest/node:${k8s_version} not found. Using fallback image ghcr.io/carvel-dev/kindest/node:${k8s_version}"
          kind create cluster --image ghcr.io/carvel-dev/kindest/node:${k8s_version}
        fi
    - name: Verify kind and k8s version
      run: |
        kind version
        kubectl version
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        path: src/github.com/${{ github.repository }}
        fetch-depth: 0
    - name: Set up go
      uses: actions/setup-go@v5
      with:
        go-version-file: src/github.com/${{ github.repository }}/go.mod
    - name: Verify go version
      run: |
        go version
    - name: Run tests
      run: |
        set -e -x

        export GOPATH=$(pwd)
        pushd src/github.com/${{ github.repository }}

        # Install ytt for build
        mkdir -p /tmp/bin
        export PATH=/tmp/bin:$PATH

        ./hack/verify-no-dirty-files.sh

        wget -O- https://carvel.dev/install.sh | K14SIO_INSTALL_BIN_DIR=/tmp/bin bash

        # Ensure that there is no existing kapp installed
        rm -f /tmp/bin/kapp

        ./hack/build-binaries.sh

        export KAPP_E2E_NAMESPACE=kapp-test
        kubectl create ns $KAPP_E2E_NAMESPACE

        ./hack/test-all.sh
